services:
  - type: web
    name: basa-school-forms
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_PIN
        sync: false